# LOCAL MANAGER for 5GCARMEN
# for deployment with NEC EC
#
# Author: Antonio Francescon 2022
# @FBK
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-www-data
  namespace: {{ .Values.namespace }}
data:
  log_level: {{ .Values.log_level }}
  # put here all other values for ConfigMap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .Release.Name }}
  template:
    metadata:
      labels:
        run: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image_repo }}:{{ .Values.image_tag }}
        name: {{ .Chart.Name }}
        env:
          # - name: RESPONSE_ROUTER_POST_ADDRESS
          #   valueFrom:
          #     configMapKeyRef:
          #       name: local-manager-cm
          #       key: response_router_post_address
          # - name: RECEIVE_TOPIC
          #   value: {{.Values.receivetopic}}
          - name: LOG_LEVEL
            value: {{ .Values.log_level }}
          - name: SUPPORT_MESSAGE_RESEND_TIMEOUT
            value: {{ .Values.sm_resend_timeout | quote }}
          - name: API_PORT
            value: {{ .Values.api_port | quote }}
          - name: RESPONSE_ROUTER_EP
            value: {{ .Values.rr_endpoint }}
          - name: RESPONSE_ROUTER_API
            value: {{ .Values.rr_api }}
          - name: RECEIVER_BROKER_TOPIC
            value: {{ .Values.receiver_topic }}
        resources: {}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.api_port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.api_port }}
    nodePort: {{ .Values.nodePort }}
  selector:
    run: {{ .Release.Name }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
