# Default values for local-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: default
image:
  repository: fbksense/local-manager
  pullPolicy: Always

service:
  type: NodePort
  port: 3277
  protocol: TCP

nodePort: 31277

image_repo: fbksense/local-manager
image_tag: v0

# LM log level
log_level: DEBUG
# Timeout before Support Message re-transmission (for the same qt code)
sm_resend_timeout: 5
# RR API port
api_port: 3277
# Response Router endpoint <IP>:<port>
rr_endpoint: 127.0.0.1:8888
# Response Router POST url
rr_api: /api/v1/rr/
# Broker topic to subscribe
receiver_topic: FROM_CARS
